CREATE DATABASE IF NOT EXISTS codeall CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE codeall;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NULL,
  cpf VARCHAR(20) NULL,
  cep VARCHAR(20) NULL,
  address VARCHAR(200) NULL,
  number VARCHAR(20) NULL,
  complement VARCHAR(100) NULL,
  district VARCHAR(120) NULL,
  city VARCHAR(120) NULL,
  created_at DATETIME NOT NULL
) ENGINE=InnoDB;
