import { Dimensions, Platform, StyleSheet } from "react-native";
import { theme } from "../../global/themes";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        width: '100%',
        paddingTop: Platform.OS === 'android' ? 30 : 0,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,   
        elevation: 5,
    },
    cabecalho: {
        width: '100%', 
        height: 200,
        justifyContent: "space-between",
        borderRadius: 10,
        padding: 0,
        paddingTop: Platform.OS === 'android' ? 40 : 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,   
        elevation: 5,
        backgroundColor: theme.colors.secundary,
    },
    boxLogo: {
        flex: 1,
        width: '100%',
        justifyContent: "space-between",
        alignItems: 'center',
        marginBottom: 20,
        
    },
    text: {
        fontSize: 16,
        color: theme.colors.black,
        textAlign: 'center',
        marginTop: -50,
        maxWidth: '90%',
        fontWeight: '500',
       
  },
     logo: {
        width: 120,
        height: 150,
        resizeMode: 'contain',
  },

  nome: { 
    fontSize: 25,
    fontWeight: '600',
    color: theme.colors.secundary,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    maxWidth: '100%',
    fontFamily: 'Aladin_400Regular',
  },
  buttonsContainer: {
    flex: 1,
    paddingHorizontal: 0,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center', 
    alignItems: 'center',
    flexWrap: 'wrap',
    marginTop: 20,
    gap: 1, 
  },
  button: {
    width: '45%',
    backgroundColor: '#fbffffff',
    paddingVertical: 20,
    marginBottom: 0, 
    marginHorizontal: 5, 
    borderWidth: 1,
    borderColor: theme.colors.secundary,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: "#000000ff",
    shadowOffset: {   width: 0, height: 2  },
    shadowOpacity: 5.25,
    shadowRadius: 4.84,
    elevation: 5,
  },
  certificadosButtonText: {
    color: '#000000ff',
    fontSize: 16, 
    fontWeight: 'bold',
  }, 
  cursosButtonText: {
    color: '#000000ff',
    fontSize: 16, 
    fontWeight: 'bold',
  },
  fundo: {
    position: 'absolute',
    top: Platform.OS === 'android' ? 30 : 0, 
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
    opacity: 0.3, 
    zIndex: -1, 
  },

  welcome: {
    fontSize: 16,
    color: theme.colors.secundary,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    maxWidth: '100%',
    fontWeight: '600',
  
  },
    MeusCursos: {
    fontSize: 35,
    color: theme.colors.black,
    textAlign: 'left',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
    maxWidth: '100%',
    fontWeight: '600',
    
  },
  

})